### ISSUE TITLE
`celebi.txt` save path

### ISSUE THREAD

**Issue by Obegg** [po5/celebi#1]
I use Windows, 
it seems like `celebi.txt` is saved on `C:\Users\User\AppData\Roaming\mpv`
but my mpv directory is on `C:\Users\User\Desktop\mpv`,
everything is inside this directory, the `scripts` and `script-opts` are there aswell,
there's is nothing on `C:\Users\User\AppData\Roaming\mpv` except the `celebi.txt`,
I would like `celebi.txt` to be saved on `C:\Users\User\Desktop\mpv`.

**Comment by po5** [comment]
Tell me if this works as expected (:

**Comment by Obegg** [comment]
Thank you!
Yes, I just tested it and it works as expected, now `celebi.txt` is saved in `C:\Users\User\Desktop\mpv`.
