### ISSUE TITLE
Trying to save 'time in ms vs not' and 'time left vs total time'

### ISSUE THREAD

**Issue by AstudilloMarillo** [po5/celebi#5]
I believe these properties are called 'timems' and 'timetotal' respectively, but they're not persisted when I put them in the persist-properties.lua. Can't find what else they're supposed to be called. Can't these properties be saved? Right now they keep getting reset upon restart when I toggle them.

**Comment by po5** [comment]
These are script options. You can persist them with script-opts=yes if you're toggling them that way. But if you're using the builtin osc's on-click toggle then it will not and cannot be reflected in the script-opts property as that's part of the script's internal state which we cannot access.  
Submit an issue with mpv if you want them to broadcast this state in some way.

I would recommend having your preferred setting in ~/script-opts/osc.conf instead.

**Comment by AstudilloMarillo** [comment]
> These are script options. You can persist them with script-opts=yes if you're toggling them that way. But if you're using the builtin osc's on-click toggle then it will not and cannot be reflected in the script-opts property as that's part of the script's internal state which we cannot access. Submit an issue with mpv if you want them to broadcast this state in some way.
> 
> I would recommend having your preferred setting in ~/script-opts/osc.conf instead.

That explains it, thanks for the answer. I'll consider submitting an issue with mpv.
